config/routes.rb
Rails.application.routes.draw do
  resources :produtos
  root 'produtos#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/produto.rb
class Produto < ApplicationRecord
  validates :nome, presence: true, uniqueness: true
  validates :preco, presence: true
  validates :quantidade, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: %i[show edit update destroy]

  helper ProdutosHelper

  # GET /produtos
  def index
    # @produtos = Produto.all
    @nome_a_buscar = params[:nome]
    @produtos = Produto.where 'nome like ?', "%#{@nome_a_buscar}%"
  end

  # GET /produtos/1
  def show; end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit; end

  # POST /produtos
  def create
    @produto = Produto.new(produto_params)

    if @produto.save
      flash[:notice] = 'Produto cadastrado com sucesso.'
      redirect_to root_url
    else
      render :new
    end
  end

  # PATCH/PUT /produtos/1
  def update
    if @produto.update(produto_params)
      flash[:notice] = 'Produto atualizado com sucesso.'
      redirect_to root_url
    else
      render :edit
    end
  end

  # DELETE /produtos/1
  def destroy
    @produto.destroy
    flash[:notice] = 'Produto removido com sucesso.'
    redirect_to produtos_url
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_produto
    @produto = Produto.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def produto_params
    params.require(:produto).permit(:nome, :descricao, :preco, :quantidade)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
  # def number_to_currency_br(number)
  #   number_to_currency(number, unit: '$ ', separator: '.', delimiter: '.')
  # end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Ninja Retro Games</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
  <%= javascript_include_tag "application", 'data-turbolinks-track': "reload" %>
</head>

<nav class="navbar navbar-expand-lg navbar-dark bg-retro">
  <div class="container">
    <!-- <a class="navbar-brand" href="#">< / ></a> -->
    <a class="navbar-brand" href="/produtos">
      <%= image_tag "logo.svg", width: "200px;" %>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown"
      aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <%= form_tag produtos_path, method: :get, class: "form-inline" do %>
      <div class="form-group">
        <%= text_field_tag :nome, @nome_a_buscar, class: "form-control mr-sm-2" %>
        <%= button_to "Buscar", nil, class: "btn btn-outline-success my-2 my-sm-0" %>
      </div>
    <% end %>
  </div>
</nav>

<body>
  <%= yield %>
</body>

</html>

app/views/page/index.html.erb
<div id="index-banner" class="parallax-container">
  <div class="section no-pad-bot">
    <div class="container">
      <br>
      <br>
      <h1 class="header center teal-text text-lighten-2">Bem vindo a Casa do Produto</h1>
      <div class="row center">
        <h5 class="header col s12 light">A modern responsive front-end framework based on Material Design</h5>
      </div>
      <div class="row center">
        <a href="http://materializecss.com/getting-started.html" id="download-button" class="btn-large waves-effect waves-light teal lighten-1">Get Started</a>
      </div>
      <br>
      <br>

    </div>
  </div>
</div>


<div class="container">
  <div class="section">

    <!--   Icon Section   -->
    <div class="row">
      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center brown-text">
            <i class="material-icons">flash_on</i>
          </h2>
          <h5 class="center">Speeds up development</h5>

          <p class="light">We did most of the heavy lifting for you to provide a default stylings that incorporate our custom components.
            Additionally, we refined animations and transitions to provide a smoother experience for developers.</p>
        </div>
      </div>

      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center brown-text">
            <i class="material-icons">group</i>
          </h2>
          <h5 class="center">User Experience Focused</h5>

          <p class="light">By utilizing elements and principles of Material Design, we were able to create a framework that incorporates components
            and animations that provide more feedback to users. Additionally, a single underlying responsive system across
            all platforms allow for a more unified user experience.</p>
        </div>
      </div>

      <div class="col s12 m4">
        <div class="icon-block">
          <h2 class="center brown-text">
            <i class="material-icons">settings</i>
          </h2>
          <h5 class="center">Easy to work with</h5>

          <p class="light">We have provided detailed documentation as well as specific code examples to help new users get started. We are
            also always open to feedback and can answer any questions a user may have about Materialize.</p>
        </div>
      </div>
    </div>

  </div>
</div>


</div>

app/views/produtos/_form.html.erb
<% if produto.errors.any? %>
  <% produto.errors.full_messages.each do |message| %>
    <div id="notice"  class="alert alert-danger" role="alert">
      <%= message %>
    </div>  
  <% end %>
<% end %>

<div class="row">

  <%= form_with(model: produto, local: true, class:"col s12") do |form| %>

    <div class="form-group">
        <%= form.label 'Nome' %>
        <%= form.text_field :nome, id: :produto_nome, class: "form-control"  %>
      </div>
    
    <div class="form-group">
      <%= form.label 'Descrição' %>
      <%= form.text_area :descricao, id: :produto_descricao, class: "form-control" %>
    </div>
    
    <div class="form-row">
      <div class="col">
        <%= form.label 'Preço' %>
        <%= form.text_field :preco, id: :produto_preco, class: "form-control" %>
      </div>
      
      <div class="col">
        <%= form.label 'Quantidade' %>
        <%= form.number_field :quantidade, id: :produto_quantidade, class: "form-control"  %>
      </div>
    </div>
    
    <div class="mt-4">
      <%= form.submit nil, :class => "btn btn-success" %>
    </div>

  <% end %>
</div>

app/views/produtos/edit.html.erb
<div class="container retro-view">
   <h2 id="view_title">Editar</h2>

    <%= render 'form', produto: @produto %>
    
</div>

app/views/produtos/index.html.erb
<div class="container retro-view">

  <% if flash[:notice] %>
    <div id="notice"  class="alert alert-success" role="alert">
      <%= flash[:notice] %>
    </div>
  <% end %>

  <div class="d-flex justify-content-between">
    <h2 id="view_title">Lista de jogos</h2>

    <%= link_to "Novo", new_produto_path, class: "btn btn-info btn-lg" %>
  </div>

  <br/>

  <% if @produtos.size == 0 %>
    <div id="not_found" class="alert alert-secondary" role="alert">
      :( Nenhum registro encontrado.
    </div>
  <% else %> 
    <table id="table_list" class="table table-hover">
      <thead>
        <tr>
          <th>Nome</th>
          <th>Descrição</th>
          <th width="10%">Preço</th>
          <th>Quantidade</th>
          <th colspan="3" :align="right">Ações</th>
        </tr>
      </thead>

      <tbody>
        <% @produtos.each do |produto| %>
          <tr>
            <td>
              <%= produto.nome %>
            </td>
            <td>
              <%= produto.descricao %>
            </td>
            <td>
              <span class="badge badge-success"> <%= number_to_currency(produto.preco, :separator => ".", :delimiter => ".") %></span>
            </td>
            <td>
              <span class="badge badge-info"><%= produto.quantidade %></span>
            </td>
            <td :align="right">
              <%= link_to '<i class="fa fa-pencil" aria-hidden="true"></i>'.html_safe, edit_produto_path(produto), class: "btn btn-outline-secondary btn-sm", id: "edit" %>
              <%= link_to '<i class="fa fa-trash-o" aria-hidden="true"></i>'.html_safe, produto, class: "btn btn-outline-danger btn-sm", id: "delete", method: :delete, data: { confirm: "Tem certeza que deseja remover?" } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/produtos/new.html.erb
<div class="container retro-view">

    <h2 id="view_title">Novo produto</h2>

    <%= render 'form', produto: @produto %>

</div>

app/views/produtos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @produto.nome %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @produto.descricao %>
</p>

<p>
  <strong>Preco:</strong>
  <%= @produto.preco %>
</p>

<p>
  <strong>Quantidade:</strong>
  <%= @produto.quantidade %>
</p>

<%= link_to 'Edit', edit_produto_path(@produto) %> |
<%= link_to 'Back', produtos_path %>